added latest chages as of 21/06/2022

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,10 +7,10 @@ rm -f configure.okay
 
 CFGERR=2
 
-echo -e "\n JNOS 2.0 ./configure script Version 1.9 - 17Apr2021, Maiko Langelaar (VE4KLM)\n"
+echo -e "\n JNOS 2.0 ./configure script Version 1.10 - 02Jan2022, Maiko Langelaar (VE4KLM)\n"
 
 # make sure the makefile is compatible with this configure script
-grep 'configure_17Apr2021_v1.9' makefile > /dev/null 2>&1 && echo "1" > makefile.okay || rm -f makefile.okay
+grep 'configure_02Jan2022_v1.10' makefile > /dev/null 2>&1 && echo "1" > makefile.okay || rm -f makefile.okay
 
 if [ -f makefile.okay ]; then
         echo -e "\tmakefile is compatible with this script\n"
@@ -43,7 +43,14 @@ fi
 
 # Warn folks RDATECLI will not be supported soon (gcc 10 and stime() no more)
 # 03Aug2020, Maiko (VE4KLM), I don't see the point, just use ntp linux side.
-grep 'define RDATECLI' config.h > /dev/null 2>&1 && echo -e "  you should #undef RDATECLI in config.h and use ntp services linux side\n  *compile will fail with gcc version 10, no point supporting anymore ?\n"
+grep 'define RDATECLI' config.h > /dev/null 2>&1 && echo -e "  remove #define RDATECLI in config.h - use ntp services linux side instead.\n   (compile fails with recent gcc versions, no point supporting anymore)\n"
+
+# 02Jan2021, Maiko (VE4KLM), #define SPEED_UP_TICK breaks timers and stuff, it
+# was experimental, probably not a great idea, need to revisit perhaps, in any
+# event, we should not allow configuration to continue if #define is present.
+#
+# This gave Bob (VE3TOK) and his group, a bit of grief for a while :(
+grep 'define SPEED_UP_TICK' config.h > /dev/null 2>&1 && echo -e "  remove #define SPEED_UP_TICK in config.h - it breaks timers and stuff.\n   (experimental from 2013, just a bad idea, get rid of it)\n" && exit 1;
 
 # Remove any temporary files generated by this script
 rm -f testcfg.c testcfg.o
